// AngularOpenMessenger/src/app/components/contact/contact.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Contact } from 'src/app/model/contact';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.sass']
})
export class ContactComponent implements OnInit {

  @Input() contact: Contact | any;

  @Input() selected: boolean | any;

  constructor() { }

  ngOnInit(): void { }

}

<div class="contact" [ngClass]="{ 'selected' : selected }">

    <div class="avatar-div">
        <img src="/assets/avatars/{{contact.avatar}}" alt="Avatar" class="avatar-img">
    </div>

    <div class="full-name">
        {{contact.fullName}}
    </div>

    <div class="status">
        {{contact.status}}
    </div>

    <div class="notification-panel">
        <span *ngIf="contact.unreadMessages > 0" class="badge">{{contact.unreadMessages }}</span>
    </div>

</div>

// react-messenger/src/components/Contact.tsx
import { Contact } from "../datamodel/Contact";
import './Contact.sass'

export function ContactComponent(properties: any) {

    let contact: Contact = properties.contact
    let selected: Boolean = properties.selected
    let onClickCallback = properties.onClick

    return <div onClick={() => onClickCallback(contact)} className={ selected ? "contact contact-selected" : "contact"} >

        <div className="contact-avatar">
            <img alt="contact's avatar" className="contact-avatar-img" src={'/assets/' + contact.avatar} />
        </div>

        <div className="contact-name">
            <p>{contact.firstName} {contact.lastName}</p>
        </div>

        <div className="contact-status">
            This is a status
        </div>

    </div>
}
